configServiceAddress:
  ip: 127.0.0.1
  port: 9001
httpOuterAddress:
  ip: http://
  port: 9003
httpInnerAddress:
  ip: 0.0.0.0
  port: 9003
moduleName: gate
instanceUuid: 9d89354b-c728-4b48-b002-a7d3b229f151
locations:
  - pathPrefix: /api
    protocol: grpc
    targetModule: router
  - pathPrefix: /mdm
    protocol: http
    targetModule: mdm-api