configServiceAddress:
  ip: 127.0.0.1
  port: 9001
httpOuterAddress:
  ip: 127.0.0.1
  port: 9003
httpInnerAddress:
  ip: 0.0.0.0
  port: 9003
moduleName: isp-gate
instanceUuid: 9d89354b-c728-4b48-b002-a7d3b229f151
routerConfig:
  routerModuleName: router
  pathPrefix: /api
  skipAuth: false
  skipExistCheck: false
